apply plugin: 'application'

mainClassName = 'tactics.lwjgl3.Lwjgl3Launcher'

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
}

sourceSets {
    main {
        java.srcDirs = ['src/main/java']
    }
}

run {
    workingDir = rootProject.file('assets').absolutePath
}
